- hosts: all
  tasks:
     - name: stop contaier
       shell: docker container stop dockeransible
     - name: remove contaier
       shell: docker container rm dockeransible
     - name: docker image removal
       shell: docker image rm -f oalalif/pipeline-demo2
     - name: create new container
       shell: docker run -itd --name dockeransible -p 80:5000 oalalif/pipeline-demo2