- hosts: all
  tasks:
    - name: stop container 
      shell: docker container stop demo-container
    - name: remove container
      shell: docker container rm demo-container
    - name: remove docker image
      shell: docker image rm oalalif/demo-2
    - name: create new container
      shell: docker container run -itd --name demo-container -p 9000:80 oalalif/demo-2